name: cleo

channels:
  - conda-forge

dependencies:
  - python <= 3.9
  - urllib3
  - certifi
  - tqdm
  - scipy
  - numpy
  - pandas
  - openpyxl
  - netcdf4
  - xarray
  - rasterio
  - rioxarray
  - geopandas
  - pint
  - pycountry
